on: [push, pull_request]

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} R ${{ matrix.r-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        r-version: [ 3.6.3, 4.0.0, 4.1.0, 4.2.0, 4.3.3, 4.4.3, release, devel ]

    steps:
      - uses: actions/checkout@v4
        
      - name: Install R
        uses: s-u/R-actions/install@v2
        with:
          r-version: ${{ matrix.r-version }}
          tools: base

      - name: Install TinyTeX
        uses: s-u/R-actions/tinytex@master

      - uses: s-u/R-actions/pkg-check@v2
        with:
          debian-deps: libssl-dev
          macos-deps: openssl
          windows-deps: openssl
          check-flags: --as-cran
